version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '../app:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=SecretPass
            - MYSQL_DATABASE=database
            - MYSQL_USER=root
            - MYSQL_PASSWORD=SecretPass
        ports:
            - '9002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '../app:/app'
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '9000:80'

    php-fpm:
        build: php-fpm
        working_dir: /app
        volumes:
            - '../app:/app'
            - './php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
